###
#   Database Settings
###
server:
   port: 9091
spring:
  jmx:
    enabled: false
  datasource:
    url: jdbc:mariadb://localhost:3306/springbootdb
    username: some
    password: some
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect