
# ==============
# open via http://localhost:9091/
# --------------
# The script uses these environment variables.
# Set them before use
# Here are examples:
# RP_FLEET_DB_PATH="/home/db/"
# ==============
version: '2'
services:
  backend:
    image: jboss/wildfly
    network_mode: host
    volumes:
      - $IT_ORGANIZER_DB_PATH:/u01/it-organizer/db/
      - $IT_ORGANIZER_PATH_TO_WAR/it-organizer-1.2.war:/opt/jboss/wildfly/standalone/deployments/it-organizer.war
      - $IT_ORGANIZER_LOGS_DIR:/u01/it-organizer/log/
    command: /opt/jboss/wildfly/bin/standalone.sh --debug 8787 -b 0.0.0.0 -bmanagement 0.0.0.0
    container_name: it-organizer-backend
    ports:
      - "8080:8080"
      - "8787:8787"
  frontend:
    image: node:8.11.3-alpine
    network_mode: host
    volumes:
      - /development/study/it-organizer/it-organizer-frontend:/app
    working_dir: /app
    command: npm start
    container_name: it-organizer-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
